# Generated by Django 5.1.7 on 2025-03-16 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pest_recognition', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlantDiseaseDetection',
        ),
    ]
